name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-dxt:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install UV
      run: |
        pip install uv
    
    - name: Install dependencies
      run: |
        make install
    
    - name: Build DXT package
      run: |
        make build-dxt
    
    - name: Build Python package
      run: |
        make build
    
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*.dxt
          dist/*.whl
          dist/*.tar.gz
        body: |
          ## 🚀 Hanzo MCP Release
          
          ### 📦 Installation Options
          
          #### Option 1: Desktop Extension (Easiest)
          Download the `.dxt` file below and double-click to install in Claude Desktop.
          
          #### Option 2: PyPI
          ```bash
          pip install hanzo-mcp
          ```
          
          #### Option 3: From Source
          ```bash
          git clone https://github.com/hanzoai/mcp
          cd mcp
          make install
          ```
          
          ### ✨ What's New
          See [CHANGELOG.md](https://github.com/hanzoai/mcp/blob/main/CHANGELOG.md) for details.
          
        draft: false
        prerelease: false
    
    - name: Upload to PyPI
      if: startsWith(github.ref, 'refs/tags/')
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        pip install twine
        twine upload dist/*.whl dist/*.tar.gz
